resilience4j:
  circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 11
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            timeLimiter:
                timeoutDuration: 1000
